# docker-compose.yml

version: '3.8'
services:

  postgres:
    image: postgres:16.1
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5433:5432'

volumes:
  postgres:
